# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/invasion_telemetry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import enum_wrapper_pb2 as pogoprotos_dot_enums_dot_enum__wrapper__pb2
from pogoprotos.enums import telemetry_ids_pb2 as pogoprotos_dot_enums_dot_telemetry__ids__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/invasion_telemetry.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n2pogoprotos/data/telemetry/invasion_telemetry.proto\x12\x19pogoprotos.data.telemetry\x1a#pogoprotos/enums/enum_wrapper.proto\x1a$pogoprotos/enums/telemetry_ids.proto\"\xa9\x03\n\x11InvasionTelemetry\x12\x45\n\x15invasion_telemetry_id\x18\x01 \x01(\x0e\x32&.pogoprotos.enums.InvasionTelemetryIds\x12?\n\x06npc_id\x18\x02 \x01(\x0e\x32/.pogoprotos.enums.EnumWrapper.InvasionCharacter\x12\x16\n\x0e\x62\x61ttle_success\x18\x03 \x01(\x08\x12&\n\x1epost_battle_friendly_remaining\x18\x04 \x01(\x05\x12#\n\x1bpost_battle_enemy_remaining\x18\x05 \x01(\x05\x12\x19\n\x11\x65ncounter_pokemon\x18\x06 \x01(\x05\x12\x19\n\x11\x65ncounter_success\x18\x07 \x01(\x08\x12\x13\n\x0binvasion_id\x18\x08 \x01(\t\x12\x19\n\x11player_tapped_npc\x18\t \x01(\x08\x12\r\n\x05radar\x18\n \x01(\t\x12\x0e\n\x06\x63urfew\x18\x0b \x01(\x08\x12\x10\n\x08\x64uration\x18\x0c \x01(\x02\x12\x10\n\x08\x64istance\x18\r \x01(\x02\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_enums_dot_enum__wrapper__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_telemetry__ids__pb2.DESCRIPTOR,])




_INVASIONTELEMETRY = _descriptor.Descriptor(
  name='InvasionTelemetry',
  full_name='pogoprotos.data.telemetry.InvasionTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='invasion_telemetry_id', full_name='pogoprotos.data.telemetry.InvasionTelemetry.invasion_telemetry_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npc_id', full_name='pogoprotos.data.telemetry.InvasionTelemetry.npc_id', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battle_success', full_name='pogoprotos.data.telemetry.InvasionTelemetry.battle_success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_battle_friendly_remaining', full_name='pogoprotos.data.telemetry.InvasionTelemetry.post_battle_friendly_remaining', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='post_battle_enemy_remaining', full_name='pogoprotos.data.telemetry.InvasionTelemetry.post_battle_enemy_remaining', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_pokemon', full_name='pogoprotos.data.telemetry.InvasionTelemetry.encounter_pokemon', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_success', full_name='pogoprotos.data.telemetry.InvasionTelemetry.encounter_success', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invasion_id', full_name='pogoprotos.data.telemetry.InvasionTelemetry.invasion_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_tapped_npc', full_name='pogoprotos.data.telemetry.InvasionTelemetry.player_tapped_npc', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radar', full_name='pogoprotos.data.telemetry.InvasionTelemetry.radar', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curfew', full_name='pogoprotos.data.telemetry.InvasionTelemetry.curfew', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='pogoprotos.data.telemetry.InvasionTelemetry.duration', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='pogoprotos.data.telemetry.InvasionTelemetry.distance', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=582,
)

_INVASIONTELEMETRY.fields_by_name['invasion_telemetry_id'].enum_type = pogoprotos_dot_enums_dot_telemetry__ids__pb2._INVASIONTELEMETRYIDS
_INVASIONTELEMETRY.fields_by_name['npc_id'].enum_type = pogoprotos_dot_enums_dot_enum__wrapper__pb2._ENUMWRAPPER_INVASIONCHARACTER
DESCRIPTOR.message_types_by_name['InvasionTelemetry'] = _INVASIONTELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvasionTelemetry = _reflection.GeneratedProtocolMessageType('InvasionTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _INVASIONTELEMETRY,
  '__module__' : 'pogoprotos.data.telemetry.invasion_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.InvasionTelemetry)
  })
_sym_db.RegisterMessage(InvasionTelemetry)


# @@protoc_insertion_point(module_scope)
