# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/news_page_telemetry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import telemetry_ids_pb2 as pogoprotos_dot_enums_dot_telemetry__ids__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/news_page_telemetry.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n3pogoprotos/data/telemetry/news_page_telemetry.proto\x12\x19pogoprotos.data.telemetry\x1a$pogoprotos/enums/telemetry_ids.proto\"W\n\x11NewsPageTelemetry\x12\x42\n\x12news_page_click_id\x18\x01 \x01(\x0e\x32&.pogoprotos.enums.NewsPageTelemetryIdsb\x06proto3'
  ,
  dependencies=[pogoprotos_dot_enums_dot_telemetry__ids__pb2.DESCRIPTOR,])




_NEWSPAGETELEMETRY = _descriptor.Descriptor(
  name='NewsPageTelemetry',
  full_name='pogoprotos.data.telemetry.NewsPageTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='news_page_click_id', full_name='pogoprotos.data.telemetry.NewsPageTelemetry.news_page_click_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=207,
)

_NEWSPAGETELEMETRY.fields_by_name['news_page_click_id'].enum_type = pogoprotos_dot_enums_dot_telemetry__ids__pb2._NEWSPAGETELEMETRYIDS
DESCRIPTOR.message_types_by_name['NewsPageTelemetry'] = _NEWSPAGETELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewsPageTelemetry = _reflection.GeneratedProtocolMessageType('NewsPageTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _NEWSPAGETELEMETRY,
  '__module__' : 'pogoprotos.data.telemetry.news_page_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.NewsPageTelemetry)
  })
_sym_db.RegisterMessage(NewsPageTelemetry)


# @@protoc_insertion_point(module_scope)
