# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/poi_submission_telemetry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import poi_image_type_pb2 as pogoprotos_dot_enums_dot_poi__image__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/poi_submission_telemetry.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n8pogoprotos/data/telemetry/poi_submission_telemetry.proto\x12\x19pogoprotos.data.telemetry\x1a%pogoprotos/enums/poi_image_type.proto\"\x9e\x06\n\x16PoiSubmissionTelemetry\x12_\n\x0cgui_event_id\x18\x01 \x01(\x0e\x32I.pogoprotos.data.telemetry.PoiSubmissionTelemetry.PoiSubmissionGuiEventId\x12\x32\n\nimage_type\x18\x02 \x01(\x0e\x32\x1e.pogoprotos.enums.PoiImageType\x12Z\n\x0e\x63\x61mera_step_id\x18\x03 \x01(\x0e\x32\x42.pogoprotos.data.telemetry.PoiSubmissionTelemetry.PoiCameraStepIds\"\xc5\x03\n\x17PoiSubmissionGuiEventId\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x18\n\x14POI_NOMINATION_ENTER\x10\x01\x12\x19\n\x15POI_TUTORIAL_COMPLETE\x10\x02\x12\x1b\n\x17POI_MAP_CHANGEDVIEW_MAP\x10\x03\x12!\n\x1dPOI_MAP_CHANGEDVIEW_SATELLITE\x10\x04\x12\x1b\n\x17POI_MAP_CENTER_LOCATION\x10\x05\x12\x14\n\x10POI_LOCATION_SET\x10\x06\x12\x1a\n\x16POI_PHOTO_CAMERA_ENTER\x10\x07\x12\x19\n\x15POI_PHOTO_CAMERA_EXIT\x10\x08\x12\x15\n\x11POI_TITLE_ENTERED\x10\t\x12\x19\n\x15POI_DESCRIPTION_ENTER\x10\n\x12\x17\n\x13POI_DETAILS_CONFIRM\x10\x0b\x12\x1c\n\x18POI_SUPPORTINGINFO_ENTER\x10\x0c\x12\x19\n\x15POI_SUBMIT_BUTTON_HIT\x10\r\x12\x17\n\x13POI_EXIT_BUTTON_HIT\x10\x0e\x12!\n\x1dPOI_NOMINATION_GUIDELINES_HIT\x10\x0f\"K\n\x10PoiCameraStepIds\x12\t\n\x05UNSET\x10\x00\x12\t\n\x05\x45NTER\x10\x01\x12\n\n\x06RETAKE\x10\x02\x12\x0b\n\x07\x43ONFIRM\x10\x03\x12\x08\n\x04\x45XIT\x10\x04\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_enums_dot_poi__image__type__pb2.DESCRIPTOR,])



_POISUBMISSIONTELEMETRY_POISUBMISSIONGUIEVENTID = _descriptor.EnumDescriptor(
  name='PoiSubmissionGuiEventId',
  full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry.PoiSubmissionGuiEventId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_NOMINATION_ENTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_TUTORIAL_COMPLETE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_MAP_CHANGEDVIEW_MAP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_MAP_CHANGEDVIEW_SATELLITE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_MAP_CENTER_LOCATION', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_LOCATION_SET', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_PHOTO_CAMERA_ENTER', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_PHOTO_CAMERA_EXIT', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_TITLE_ENTERED', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_DESCRIPTION_ENTER', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_DETAILS_CONFIRM', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_SUPPORTINGINFO_ENTER', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_SUBMIT_BUTTON_HIT', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_EXIT_BUTTON_HIT', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POI_NOMINATION_GUIDELINES_HIT', index=15, number=15,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=395,
  serialized_end=848,
)
_sym_db.RegisterEnumDescriptor(_POISUBMISSIONTELEMETRY_POISUBMISSIONGUIEVENTID)

_POISUBMISSIONTELEMETRY_POICAMERASTEPIDS = _descriptor.EnumDescriptor(
  name='PoiCameraStepIds',
  full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry.PoiCameraStepIds',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETAKE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIRM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=850,
  serialized_end=925,
)
_sym_db.RegisterEnumDescriptor(_POISUBMISSIONTELEMETRY_POICAMERASTEPIDS)


_POISUBMISSIONTELEMETRY = _descriptor.Descriptor(
  name='PoiSubmissionTelemetry',
  full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gui_event_id', full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry.gui_event_id', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry.image_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_step_id', full_name='pogoprotos.data.telemetry.PoiSubmissionTelemetry.camera_step_id', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POISUBMISSIONTELEMETRY_POISUBMISSIONGUIEVENTID,
    _POISUBMISSIONTELEMETRY_POICAMERASTEPIDS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=925,
)

_POISUBMISSIONTELEMETRY.fields_by_name['gui_event_id'].enum_type = _POISUBMISSIONTELEMETRY_POISUBMISSIONGUIEVENTID
_POISUBMISSIONTELEMETRY.fields_by_name['image_type'].enum_type = pogoprotos_dot_enums_dot_poi__image__type__pb2._POIIMAGETYPE
_POISUBMISSIONTELEMETRY.fields_by_name['camera_step_id'].enum_type = _POISUBMISSIONTELEMETRY_POICAMERASTEPIDS
_POISUBMISSIONTELEMETRY_POISUBMISSIONGUIEVENTID.containing_type = _POISUBMISSIONTELEMETRY
_POISUBMISSIONTELEMETRY_POICAMERASTEPIDS.containing_type = _POISUBMISSIONTELEMETRY
DESCRIPTOR.message_types_by_name['PoiSubmissionTelemetry'] = _POISUBMISSIONTELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoiSubmissionTelemetry = _reflection.GeneratedProtocolMessageType('PoiSubmissionTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _POISUBMISSIONTELEMETRY,
  '__module__' : 'pogoprotos.data.telemetry.poi_submission_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.PoiSubmissionTelemetry)
  })
_sym_db.RegisterMessage(PoiSubmissionTelemetry)


# @@protoc_insertion_point(module_scope)
