# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/telemetry/pokestop_reward.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/telemetry/pokestop_reward.proto',
  package='pogoprotos.data.telemetry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n/pogoprotos/data/telemetry/pokestop_reward.proto\x12\x19pogoprotos.data.telemetry\"5\n\x0ePokestopReward\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x12\n\nitem_count\x18\x02 \x01(\x05\x62\x06proto3'
)




_POKESTOPREWARD = _descriptor.Descriptor(
  name='PokestopReward',
  full_name='pogoprotos.data.telemetry.PokestopReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='pogoprotos.data.telemetry.PokestopReward.item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_count', full_name='pogoprotos.data.telemetry.PokestopReward.item_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['PokestopReward'] = _POKESTOPREWARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PokestopReward = _reflection.GeneratedProtocolMessageType('PokestopReward', (_message.Message,), {
  'DESCRIPTOR' : _POKESTOPREWARD,
  '__module__' : 'pogoprotos.data.telemetry.pokestop_reward_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.telemetry.PokestopReward)
  })
_sym_db.RegisterMessage(PokestopReward)


# @@protoc_insertion_point(module_scope)
