# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/fitness/fitness_report.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.fitness import fitness_metrics_pb2 as pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/fitness/fitness_report.proto',
  package='pogoprotos.data.fitness',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n,pogoprotos/data/fitness/fitness_report.proto\x12\x17pogoprotos.data.fitness\x1a-pogoprotos/data/fitness/fitness_metrics.proto\"\xa5\x01\n\rFitnessReport\x12\x1d\n\x13\x64\x61y_offset_from_now\x18\x01 \x01(\x05H\x00\x12\x1e\n\x14week_offset_from_now\x18\x02 \x01(\x05H\x00\x12\x38\n\x07metrics\x18\n \x01(\x0b\x32\'.pogoprotos.data.fitness.FitnessMetrics\x12\x11\n\tgame_data\x18\x0b \x01(\x0c\x42\x08\n\x06Windowb\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2.DESCRIPTOR,])




_FITNESSREPORT = _descriptor.Descriptor(
  name='FitnessReport',
  full_name='pogoprotos.data.fitness.FitnessReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day_offset_from_now', full_name='pogoprotos.data.fitness.FitnessReport.day_offset_from_now', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='week_offset_from_now', full_name='pogoprotos.data.fitness.FitnessReport.week_offset_from_now', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='pogoprotos.data.fitness.FitnessReport.metrics', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_data', full_name='pogoprotos.data.fitness.FitnessReport.game_data', index=3,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Window', full_name='pogoprotos.data.fitness.FitnessReport.Window',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=121,
  serialized_end=286,
)

_FITNESSREPORT.fields_by_name['metrics'].message_type = pogoprotos_dot_data_dot_fitness_dot_fitness__metrics__pb2._FITNESSMETRICS
_FITNESSREPORT.oneofs_by_name['Window'].fields.append(
  _FITNESSREPORT.fields_by_name['day_offset_from_now'])
_FITNESSREPORT.fields_by_name['day_offset_from_now'].containing_oneof = _FITNESSREPORT.oneofs_by_name['Window']
_FITNESSREPORT.oneofs_by_name['Window'].fields.append(
  _FITNESSREPORT.fields_by_name['week_offset_from_now'])
_FITNESSREPORT.fields_by_name['week_offset_from_now'].containing_oneof = _FITNESSREPORT.oneofs_by_name['Window']
DESCRIPTOR.message_types_by_name['FitnessReport'] = _FITNESSREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FitnessReport = _reflection.GeneratedProtocolMessageType('FitnessReport', (_message.Message,), {
  'DESCRIPTOR' : _FITNESSREPORT,
  '__module__' : 'pogoprotos.data.fitness.fitness_report_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.fitness.FitnessReport)
  })
_sym_db.RegisterMessage(FitnessReport)


# @@protoc_insertion_point(module_scope)
