version: "3.4"

volumes:
  pre-commit-cache:
    name: pre-commit-cache

services:
  mapadroid-dev:
    image: mapadroid-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_test
    # Use an empty entrypoint and mount local sources into container so that a simple
    # `docker-compose run --service-ports python3 start.py` can be used to test current
    # development in a defined environment.
    # `docker-compose run bash` launch a shell inside the container.
    entrypoint: ""
    volumes:
      - ./:/usr/src/app:rw
      - pre-commit-cache:/home/dockuser/.cache/pre-commit
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8080:8080"
    env_file:
      - .dev.env
    tty: true
    command: ["bash"]

  mariadb:
    image: mariadb:10.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file:
      - .dev.env
