# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gamefitness/game_fitness_action_request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.networking.game.gamefitness import game_fitness_action_pb2 as pogoprotos_dot_networking_dot_game_dot_gamefitness_dot_game__fitness__action__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gamefitness/game_fitness_action_request.proto',
  package='pogoprotos.networking.game.gamefitness',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nHpogoprotos/networking/game/gamefitness/game_fitness_action_request.proto\x12&pogoprotos.networking.game.gamefitness\x1a@pogoprotos/networking/game/gamefitness/game_fitness_action.proto\"\x84\x01\n\x18GameFitnessActionRequest\x12O\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x39.pogoprotos.networking.game.gamefitness.GameFitnessAction\x12\x17\n\x0frequest_message\x18\x02 \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_networking_dot_game_dot_gamefitness_dot_game__fitness__action__pb2.DESCRIPTOR,])




_GAMEFITNESSACTIONREQUEST = _descriptor.Descriptor(
  name='GameFitnessActionRequest',
  full_name='pogoprotos.networking.game.gamefitness.GameFitnessActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='pogoprotos.networking.game.gamefitness.GameFitnessActionRequest.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_message', full_name='pogoprotos.networking.game.gamefitness.GameFitnessActionRequest.request_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=315,
)

_GAMEFITNESSACTIONREQUEST.fields_by_name['request_type'].enum_type = pogoprotos_dot_networking_dot_game_dot_gamefitness_dot_game__fitness__action__pb2._GAMEFITNESSACTION
DESCRIPTOR.message_types_by_name['GameFitnessActionRequest'] = _GAMEFITNESSACTIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameFitnessActionRequest = _reflection.GeneratedProtocolMessageType('GameFitnessActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEFITNESSACTIONREQUEST,
  '__module__' : 'pogoprotos.networking.game.gamefitness.game_fitness_action_request_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.game.gamefitness.GameFitnessActionRequest)
  })
_sym_db.RegisterMessage(GameFitnessActionRequest)


# @@protoc_insertion_point(module_scope)
