from enum import IntEnum


class MappingManagerDevicemappingKey(IntEnum):
    LAST_MODE = 0,
    ACCOUNT_INDEX = 1,
    JOB_ACTIVE = 2,
    WALKER_AREA_INDEX = 3,
    FINISHED = 4,
    LAST_LOCATION_TIME = 5,
    LAST_CLEANUP_TIME = 6,
    LAST_LOCATION = 7,
    SCREENSHOT_TYPE = 8,
    STARTCOORDS_OF_WALKER = 9
    RESTART_POGO = 10,
    POST_TURN_SCREEN_ON_DELAY = 11,
    CLEAR_GAME_DATA = 12,
    SCREENSHOT_QUALITY = 13
    POST_SCREENSHOT_DELAY = 14,
    POST_POGO_START_DELAY = 15
    SCREENSHOT_X_OFFSET = 16,
    SCREENSHOT_Y_OFFSET = 17,
    MITM_WAIT_TIMEOUT = 19,
    RESTART_THRESH = 20,
    REBOOT_THRESH = 21,
    REBOOT = 22
    INJECTION_THRESH_REBOOT = 23,
    POST_TELEPORT_DELAY = 24
    COOLDOWN_SLEEP = 25
    WALK_AFTER_TELEPORT_DISTANCE = 26
    POST_WALK_DELAY = 27
    ACCOUNT_ROTATION = 28
    VPS_DELAY = 30
    ROTATION_WAITTIME = 31
    LAST_ACTION_TIME = 32
    SCREENDETECTION = 33
    ROTATE_ON_LVL_30 = 34
    INVENTORY_CLEAR_ROUNDS = 36
    GGL_LOGIN_MAIL = 38
    LAST_QUESTCLEAR_TIME = 39
    ENHANCED_MODE_QUEST_SAFE_ITEMS = 40
    SOFTBAR_ENABLED = 42
    EXTENDED_PERMISSION_TOGGLING = 43
