# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/responses/opt_out_push_notification_category_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/responses/opt_out_push_notification_category_response.proto',
  package='pogoprotos.networking.platform.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nZpogoprotos/networking/platform/responses/opt_out_push_notification_category_response.proto\x12(pogoprotos.networking.platform.responses\"(\n&OptOutPushNotificationCategoryResponseb\x06proto3'
)




_OPTOUTPUSHNOTIFICATIONCATEGORYRESPONSE = _descriptor.Descriptor(
  name='OptOutPushNotificationCategoryResponse',
  full_name='pogoprotos.networking.platform.responses.OptOutPushNotificationCategoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['OptOutPushNotificationCategoryResponse'] = _OPTOUTPUSHNOTIFICATIONCATEGORYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptOutPushNotificationCategoryResponse = _reflection.GeneratedProtocolMessageType('OptOutPushNotificationCategoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPTOUTPUSHNOTIFICATIONCATEGORYRESPONSE,
  '__module__' : 'pogoprotos.networking.platform.responses.opt_out_push_notification_category_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.responses.OptOutPushNotificationCategoryResponse)
  })
_sym_db.RegisterMessage(OptOutPushNotificationCategoryResponse)


# @@protoc_insertion_point(module_scope)
