# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/gmt_settings.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/gmt_settings.proto',
  package='pogoprotos.settings',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&pogoprotos/settings/gmt_settings.proto\x12\x13pogoprotos.settings\",\n\x0bGmtSettings\x12\x1d\n\x15\x65nable_gmtdownload_v2\x18\x01 \x01(\x08\x62\x06proto3'
)




_GMTSETTINGS = _descriptor.Descriptor(
  name='GmtSettings',
  full_name='pogoprotos.settings.GmtSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_gmtdownload_v2', full_name='pogoprotos.settings.GmtSettings.enable_gmtdownload_v2', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['GmtSettings'] = _GMTSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GmtSettings = _reflection.GeneratedProtocolMessageType('GmtSettings', (_message.Message,), {
  'DESCRIPTOR' : _GMTSETTINGS,
  '__module__' : 'pogoprotos.settings.gmt_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.GmtSettings)
  })
_sym_db.RegisterMessage(GmtSettings)


# @@protoc_insertion_point(module_scope)
