# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/buddy/buddy_multiplayer_time_to_get_session.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/buddy/buddy_multiplayer_time_to_get_session.proto',
  package='pogoprotos.data.buddy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nApogoprotos/data/buddy/buddy_multiplayer_time_to_get_session.proto\x12\x15pogoprotos.data.buddy\"T\n BuddyMultiplayerTimeToGetSession\x12\x13\n\x0btest_number\x18\x01 \x01(\x05\x12\x1b\n\x13time_to_get_session\x18\x02 \x01(\x03\x62\x06proto3'
)




_BUDDYMULTIPLAYERTIMETOGETSESSION = _descriptor.Descriptor(
  name='BuddyMultiplayerTimeToGetSession',
  full_name='pogoprotos.data.buddy.BuddyMultiplayerTimeToGetSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_number', full_name='pogoprotos.data.buddy.BuddyMultiplayerTimeToGetSession.test_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_to_get_session', full_name='pogoprotos.data.buddy.BuddyMultiplayerTimeToGetSession.time_to_get_session', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['BuddyMultiplayerTimeToGetSession'] = _BUDDYMULTIPLAYERTIMETOGETSESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BuddyMultiplayerTimeToGetSession = _reflection.GeneratedProtocolMessageType('BuddyMultiplayerTimeToGetSession', (_message.Message,), {
  'DESCRIPTOR' : _BUDDYMULTIPLAYERTIMETOGETSESSION,
  '__module__' : 'pogoprotos.data.buddy.buddy_multiplayer_time_to_get_session_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.buddy.BuddyMultiplayerTimeToGetSession)
  })
_sym_db.RegisterMessage(BuddyMultiplayerTimeToGetSession)


# @@protoc_insertion_point(module_scope)
