# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/capture/capture_probability.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.inventory.item import item_id_pb2 as pogoprotos_dot_inventory_dot_item_dot_item__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/capture/capture_probability.proto',
  package='pogoprotos.data.capture',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n1pogoprotos/data/capture/capture_probability.proto\x12\x17pogoprotos.data.capture\x1a\'pogoprotos/inventory/item/item_id.proto\"\x95\x01\n\x12\x43\x61ptureProbability\x12<\n\rpokeball_type\x18\x01 \x03(\x0e\x32!.pogoprotos.inventory.item.ItemIdB\x02\x10\x01\x12\x1f\n\x13\x63\x61pture_probability\x18\x02 \x03(\x02\x42\x02\x10\x01\x12 \n\x18reticle_difficulty_scale\x18\x0c \x01(\x01\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_inventory_dot_item_dot_item__id__pb2.DESCRIPTOR,])




_CAPTUREPROBABILITY = _descriptor.Descriptor(
  name='CaptureProbability',
  full_name='pogoprotos.data.capture.CaptureProbability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokeball_type', full_name='pogoprotos.data.capture.CaptureProbability.pokeball_type', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capture_probability', full_name='pogoprotos.data.capture.CaptureProbability.capture_probability', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reticle_difficulty_scale', full_name='pogoprotos.data.capture.CaptureProbability.reticle_difficulty_scale', index=2,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=269,
)

_CAPTUREPROBABILITY.fields_by_name['pokeball_type'].enum_type = pogoprotos_dot_inventory_dot_item_dot_item__id__pb2._ITEMID
DESCRIPTOR.message_types_by_name['CaptureProbability'] = _CAPTUREPROBABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CaptureProbability = _reflection.GeneratedProtocolMessageType('CaptureProbability', (_message.Message,), {
  'DESCRIPTOR' : _CAPTUREPROBABILITY,
  '__module__' : 'pogoprotos.data.capture.capture_probability_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.capture.CaptureProbability)
  })
_sym_db.RegisterMessage(CaptureProbability)


_CAPTUREPROBABILITY.fields_by_name['pokeball_type']._options = None
_CAPTUREPROBABILITY.fields_by_name['capture_probability']._options = None
# @@protoc_insertion_point(module_scope)
