# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/condition_type.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/condition_type.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n%pogoprotos/enums/condition_type.proto\x12\x10pogoprotos.enums*\xa1\x01\n\rConditionType\x12\x13\n\x0fUNSET_CONDITION\x10\x00\x12\x19\n\x15WITH_POKEMON_CP_LIMIT\x10\x01\x12\x15\n\x11WITH_PLAYER_LEVEL\x10\x02\x12\x15\n\x11WITH_POKEMON_TYPE\x10\x03\x12\x19\n\x15WITH_POKEMON_CATEGORY\x10\x04\x12\x17\n\x13WITH_UNIQUE_POKEMON\x10\x05\x62\x06proto3'
)

_CONDITIONTYPE = _descriptor.EnumDescriptor(
  name='ConditionType',
  full_name='pogoprotos.enums.ConditionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET_CONDITION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITH_POKEMON_CP_LIMIT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITH_PLAYER_LEVEL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITH_POKEMON_TYPE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITH_POKEMON_CATEGORY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITH_UNIQUE_POKEMON', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=60,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_CONDITIONTYPE)

ConditionType = enum_type_wrapper.EnumTypeWrapper(_CONDITIONTYPE)
UNSET_CONDITION = 0
WITH_POKEMON_CP_LIMIT = 1
WITH_PLAYER_LEVEL = 2
WITH_POKEMON_TYPE = 3
WITH_POKEMON_CATEGORY = 4
WITH_UNIQUE_POKEMON = 5


DESCRIPTOR.enum_types_by_name['ConditionType'] = _CONDITIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
