# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/complete_snapshot_session_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/complete_snapshot_session_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nOpogoprotos/networking/requests/messages/complete_snapshot_session_message.proto\x12\'pogoprotos.networking.requests.messages\"T\n\x1e\x43ompleteSnapshotSessionMessage\x12\x18\n\x10photo_pokemon_id\x18\x01 \x01(\x06\x12\x18\n\x10num_photos_taken\x18\x02 \x01(\x05\x62\x06proto3'
)




_COMPLETESNAPSHOTSESSIONMESSAGE = _descriptor.Descriptor(
  name='CompleteSnapshotSessionMessage',
  full_name='pogoprotos.networking.requests.messages.CompleteSnapshotSessionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo_pokemon_id', full_name='pogoprotos.networking.requests.messages.CompleteSnapshotSessionMessage.photo_pokemon_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_photos_taken', full_name='pogoprotos.networking.requests.messages.CompleteSnapshotSessionMessage.num_photos_taken', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['CompleteSnapshotSessionMessage'] = _COMPLETESNAPSHOTSESSIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompleteSnapshotSessionMessage = _reflection.GeneratedProtocolMessageType('CompleteSnapshotSessionMessage', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETESNAPSHOTSESSIONMESSAGE,
  '__module__' : 'pogoprotos.networking.requests.messages.complete_snapshot_session_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.CompleteSnapshotSessionMessage)
  })
_sym_db.RegisterMessage(CompleteSnapshotSessionMessage)


# @@protoc_insertion_point(module_scope)
