# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/create_buddy_multiplayer_session_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/create_buddy_multiplayer_session_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nVpogoprotos/networking/requests/messages/create_buddy_multiplayer_session_message.proto\x12\'pogoprotos.networking.requests.messages\"&\n$CreateBuddyMultiplayerSessionMessageb\x06proto3'
)




_CREATEBUDDYMULTIPLAYERSESSIONMESSAGE = _descriptor.Descriptor(
  name='CreateBuddyMultiplayerSessionMessage',
  full_name='pogoprotos.networking.requests.messages.CreateBuddyMultiplayerSessionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['CreateBuddyMultiplayerSessionMessage'] = _CREATEBUDDYMULTIPLAYERSESSIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateBuddyMultiplayerSessionMessage = _reflection.GeneratedProtocolMessageType('CreateBuddyMultiplayerSessionMessage', (_message.Message,), {
  'DESCRIPTOR' : _CREATEBUDDYMULTIPLAYERSESSIONMESSAGE,
  '__module__' : 'pogoprotos.networking.requests.messages.create_buddy_multiplayer_session_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.CreateBuddyMultiplayerSessionMessage)
  })
_sym_db.RegisterMessage(CreateBuddyMultiplayerSessionMessage)


# @@protoc_insertion_point(module_scope)
