# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/encounter_photobomb_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/encounter_photobomb_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nIpogoprotos/networking/requests/messages/encounter_photobomb_message.proto\x12\'pogoprotos.networking.requests.messages\"M\n\x19\x45ncounterPhotobombMessage\x12\x14\n\x0c\x65ncounter_id\x18\x01 \x01(\x06\x12\x1a\n\x12\x65ncounter_location\x18\x02 \x01(\tb\x06proto3'
)




_ENCOUNTERPHOTOBOMBMESSAGE = _descriptor.Descriptor(
  name='EncounterPhotobombMessage',
  full_name='pogoprotos.networking.requests.messages.EncounterPhotobombMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encounter_id', full_name='pogoprotos.networking.requests.messages.EncounterPhotobombMessage.encounter_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encounter_location', full_name='pogoprotos.networking.requests.messages.EncounterPhotobombMessage.encounter_location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['EncounterPhotobombMessage'] = _ENCOUNTERPHOTOBOMBMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncounterPhotobombMessage = _reflection.GeneratedProtocolMessageType('EncounterPhotobombMessage', (_message.Message,), {
  'DESCRIPTOR' : _ENCOUNTERPHOTOBOMBMESSAGE,
  '__module__' : 'pogoprotos.networking.requests.messages.encounter_photobomb_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.EncounterPhotobombMessage)
  })
_sym_db.RegisterMessage(EncounterPhotobombMessage)


# @@protoc_insertion_point(module_scope)
