"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import mapadroid.grpc.compiled.shared as shared
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class IncrementLoginTrackingByOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_FIELD_NUMBER: builtins.int
    @property
    def worker(self) -> shared.Worker_pb2.Worker: ...
    def __init__(
        self,
        *,
        worker: shared.Worker_pb2.Worker | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> None: ...

global___IncrementLoginTrackingByOriginRequest = IncrementLoginTrackingByOriginRequest

@typing_extensions.final
class IncrementLoginTrackingByOriginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INCREMENTED_FIELD_NUMBER: builtins.int
    incremented: builtins.bool
    def __init__(
        self,
        *,
        incremented: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["incremented", b"incremented"]) -> None: ...

global___IncrementLoginTrackingByOriginResponse = IncrementLoginTrackingByOriginResponse

@typing_extensions.final
class GetQuestLayerToScanOfOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_FIELD_NUMBER: builtins.int
    @property
    def worker(self) -> shared.Worker_pb2.Worker: ...
    def __init__(
        self,
        *,
        worker: shared.Worker_pb2.Worker | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> None: ...

global___GetQuestLayerToScanOfOriginRequest = GetQuestLayerToScanOfOriginRequest

@typing_extensions.final
class GetQuestLayerToScanOfOriginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAYER_FIELD_NUMBER: builtins.int
    layer: builtins.int
    def __init__(
        self,
        *,
        layer: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_layer", b"_layer", "layer", b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_layer", b"_layer", "layer", b"layer"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_layer", b"_layer"]) -> typing_extensions.Literal["layer"] | None: ...

global___GetQuestLayerToScanOfOriginResponse = GetQuestLayerToScanOfOriginResponse

@typing_extensions.final
class IsRoutemanagerOfOriginLevelmodeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_FIELD_NUMBER: builtins.int
    @property
    def worker(self) -> shared.Worker_pb2.Worker: ...
    def __init__(
        self,
        *,
        worker: shared.Worker_pb2.Worker | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> None: ...

global___IsRoutemanagerOfOriginLevelmodeRequest = IsRoutemanagerOfOriginLevelmodeRequest

@typing_extensions.final
class IsRoutemanagerOfOriginLevelmodeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_LEVELMODE_FIELD_NUMBER: builtins.int
    is_levelmode: builtins.bool
    def __init__(
        self,
        *,
        is_levelmode: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_levelmode", b"is_levelmode"]) -> None: ...

global___IsRoutemanagerOfOriginLevelmodeResponse = IsRoutemanagerOfOriginLevelmodeResponse

@typing_extensions.final
class GetSafeItemsNotToDeleteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_FIELD_NUMBER: builtins.int
    @property
    def worker(self) -> shared.Worker_pb2.Worker: ...
    def __init__(
        self,
        *,
        worker: shared.Worker_pb2.Worker | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker", b"worker"]) -> None: ...

global___GetSafeItemsNotToDeleteRequest = GetSafeItemsNotToDeleteRequest

@typing_extensions.final
class GetSafeItemsNotToDeleteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEM_IDS_FIELD_NUMBER: builtins.int
    @property
    def item_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        item_ids: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["item_ids", b"item_ids"]) -> None: ...

global___GetSafeItemsNotToDeleteResponse = GetSafeItemsNotToDeleteResponse

@typing_extensions.final
class GetAllowedAuthenticationCredentialsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTH_LEVEL_FIELD_NUMBER: builtins.int
    auth_level: builtins.int
    def __init__(
        self,
        *,
        auth_level: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth_level", b"auth_level"]) -> None: ...

global___GetAllowedAuthenticationCredentialsRequest = GetAllowedAuthenticationCredentialsRequest

@typing_extensions.final
class AuthCredentialEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    AUTH_LEVEL_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    auth_level: builtins.int
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
        auth_level: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth_level", b"auth_level", "password", b"password", "username", b"username"]) -> None: ...

global___AuthCredentialEntry = AuthCredentialEntry

@typing_extensions.final
class GetAllowedAuthenticationCredentialsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class AllowedCredentialsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___AuthCredentialEntry: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___AuthCredentialEntry | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ALLOWED_CREDENTIALS_FIELD_NUMBER: builtins.int
    @property
    def allowed_credentials(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___AuthCredentialEntry]:
        """Map where username is the key, value is"""
    def __init__(
        self,
        *,
        allowed_credentials: collections.abc.Mapping[builtins.str, global___AuthCredentialEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["allowed_credentials", b"allowed_credentials"]) -> None: ...

global___GetAllowedAuthenticationCredentialsResponse = GetAllowedAuthenticationCredentialsResponse

@typing_extensions.final
class GetAllLoadedOriginsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetAllLoadedOriginsRequest = GetAllLoadedOriginsRequest

@typing_extensions.final
class GetAllLoadedOriginsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOADED_ORIGINS_FIELD_NUMBER: builtins.int
    @property
    def loaded_origins(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """simply a list of origins with configurations loaded"""
    def __init__(
        self,
        *,
        loaded_origins: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["loaded_origins", b"loaded_origins"]) -> None: ...

global___GetAllLoadedOriginsResponse = GetAllLoadedOriginsResponse
