# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/battle_hub_order_settings.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/battle_hub_order_settings.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n:pogoprotos/settings/master/battle_hub_order_settings.proto\x12\x1apogoprotos.settings.master\"\x9a\x07\n\x16\x42\x61ttleHubOrderSettings\x12S\n\x07section\x18\x01 \x03(\x0b\x32\x42.pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings\x12V\n\rsection_group\x18\x02 \x03(\x0b\x32?.pogoprotos.settings.master.BattleHubOrderSettings.SectionGroup\x1at\n\x0cSectionGroup\x12\x64\n\x07section\x18\x01 \x03(\x0e\x32S.pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.BattleHubSection\x1a\xdc\x04\n\x0fSectionSettings\x12i\n\x0cmain_section\x18\x01 \x01(\x0e\x32S.pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.BattleHubSection\x12j\n\nsubsection\x18\x02 \x03(\x0e\x32V.pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.BattleHubSubsection\"\xb1\x01\n\x10\x42\x61ttleHubSection\x12\x11\n\rSECTION_UNSET\x10\x00\x12\x15\n\x11SECTION_VS_SEEKER\x10\x01\x12\x17\n\x13SECTION_CURR_SEASON\x10\x02\x12\x17\n\x13SECTION_LAST_SEASON\x10\x03\x12\x12\n\x0eSECTION_NEARBY\x10\x04\x12\x18\n\x14SECTION_TEAM_LEADERS\x10\x05\x12\x13\n\x0fSECTION_QR_CODE\x10\x06\"\xbd\x01\n\x13\x42\x61ttleHubSubsection\x12\x14\n\x10SUBSECTION_UNSET\x10\x00\x12\x1a\n\x16SUBSECTION_VS_CHARGING\x10\x01\x12\x16\n\x12SUBSECTION_VS_FREE\x10\x02\x12\x19\n\x15SUBSECTION_VS_PREMIUM\x10\x03\x12\"\n\x1eSUBSECTION_NEARBY_TEAM_LEADERS\x10\x04\x12\x1d\n\x19SUBSECTION_NEARBY_QR_CODE\x10\x05\x62\x06proto3'
)



_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION = _descriptor.EnumDescriptor(
  name='BattleHubSection',
  full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.BattleHubSection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SECTION_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_VS_SEEKER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_CURR_SEASON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_LAST_SEASON', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_NEARBY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_TEAM_LEADERS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTION_QR_CODE', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=644,
  serialized_end=821,
)
_sym_db.RegisterEnumDescriptor(_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION)

_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSUBSECTION = _descriptor.EnumDescriptor(
  name='BattleHubSubsection',
  full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.BattleHubSubsection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_VS_CHARGING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_VS_FREE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_VS_PREMIUM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_NEARBY_TEAM_LEADERS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUBSECTION_NEARBY_QR_CODE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=824,
  serialized_end=1013,
)
_sym_db.RegisterEnumDescriptor(_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSUBSECTION)


_BATTLEHUBORDERSETTINGS_SECTIONGROUP = _descriptor.Descriptor(
  name='SectionGroup',
  full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionGroup.section', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=406,
)

_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS = _descriptor.Descriptor(
  name='SectionSettings',
  full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_section', full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.main_section', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subsection', full_name='pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings.subsection', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION,
    _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSUBSECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=1013,
)

_BATTLEHUBORDERSETTINGS = _descriptor.Descriptor(
  name='BattleHubOrderSettings',
  full_name='pogoprotos.settings.master.BattleHubOrderSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='section', full_name='pogoprotos.settings.master.BattleHubOrderSettings.section', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='section_group', full_name='pogoprotos.settings.master.BattleHubOrderSettings.section_group', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BATTLEHUBORDERSETTINGS_SECTIONGROUP, _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=1013,
)

_BATTLEHUBORDERSETTINGS_SECTIONGROUP.fields_by_name['section'].enum_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION
_BATTLEHUBORDERSETTINGS_SECTIONGROUP.containing_type = _BATTLEHUBORDERSETTINGS
_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS.fields_by_name['main_section'].enum_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION
_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS.fields_by_name['subsection'].enum_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSUBSECTION
_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS.containing_type = _BATTLEHUBORDERSETTINGS
_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSECTION.containing_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS
_BATTLEHUBORDERSETTINGS_SECTIONSETTINGS_BATTLEHUBSUBSECTION.containing_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS
_BATTLEHUBORDERSETTINGS.fields_by_name['section'].message_type = _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS
_BATTLEHUBORDERSETTINGS.fields_by_name['section_group'].message_type = _BATTLEHUBORDERSETTINGS_SECTIONGROUP
DESCRIPTOR.message_types_by_name['BattleHubOrderSettings'] = _BATTLEHUBORDERSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BattleHubOrderSettings = _reflection.GeneratedProtocolMessageType('BattleHubOrderSettings', (_message.Message,), {

  'SectionGroup' : _reflection.GeneratedProtocolMessageType('SectionGroup', (_message.Message,), {
    'DESCRIPTOR' : _BATTLEHUBORDERSETTINGS_SECTIONGROUP,
    '__module__' : 'pogoprotos.settings.master.battle_hub_order_settings_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.BattleHubOrderSettings.SectionGroup)
    })
  ,

  'SectionSettings' : _reflection.GeneratedProtocolMessageType('SectionSettings', (_message.Message,), {
    'DESCRIPTOR' : _BATTLEHUBORDERSETTINGS_SECTIONSETTINGS,
    '__module__' : 'pogoprotos.settings.master.battle_hub_order_settings_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.BattleHubOrderSettings.SectionSettings)
    })
  ,
  'DESCRIPTOR' : _BATTLEHUBORDERSETTINGS,
  '__module__' : 'pogoprotos.settings.master.battle_hub_order_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.BattleHubOrderSettings)
  })
_sym_db.RegisterMessage(BattleHubOrderSettings)
_sym_db.RegisterMessage(BattleHubOrderSettings.SectionGroup)
_sym_db.RegisterMessage(BattleHubOrderSettings.SectionSettings)


# @@protoc_insertion_point(module_scope)
