# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/gender_settings.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import pokemon_id_pb2 as pogoprotos_dot_enums_dot_pokemon__id__pb2
from pogoprotos.settings.master.pokemon import pokemon_gender_settings_pb2 as pogoprotos_dot_settings_dot_master_dot_pokemon_dot_pokemon__gender__settings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/gender_settings.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n0pogoprotos/settings/master/gender_settings.proto\x12\x1apogoprotos.settings.master\x1a!pogoprotos/enums/pokemon_id.proto\x1a@pogoprotos/settings/master/pokemon/pokemon_gender_settings.proto\"\x89\x01\n\x0eGenderSettings\x12,\n\x07pokemon\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.PokemonId\x12I\n\x06gender\x18\x02 \x01(\x0b\x32\x39.pogoprotos.settings.master.pokemon.PokemonGenderSettingsb\x06proto3'
  ,
  dependencies=[pogoprotos_dot_enums_dot_pokemon__id__pb2.DESCRIPTOR,pogoprotos_dot_settings_dot_master_dot_pokemon_dot_pokemon__gender__settings__pb2.DESCRIPTOR,])




_GENDERSETTINGS = _descriptor.Descriptor(
  name='GenderSettings',
  full_name='pogoprotos.settings.master.GenderSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='pogoprotos.settings.master.GenderSettings.pokemon', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='pogoprotos.settings.master.GenderSettings.gender', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=319,
)

_GENDERSETTINGS.fields_by_name['pokemon'].enum_type = pogoprotos_dot_enums_dot_pokemon__id__pb2._POKEMONID
_GENDERSETTINGS.fields_by_name['gender'].message_type = pogoprotos_dot_settings_dot_master_dot_pokemon_dot_pokemon__gender__settings__pb2._POKEMONGENDERSETTINGS
DESCRIPTOR.message_types_by_name['GenderSettings'] = _GENDERSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenderSettings = _reflection.GeneratedProtocolMessageType('GenderSettings', (_message.Message,), {
  'DESCRIPTOR' : _GENDERSETTINGS,
  '__module__' : 'pogoprotos.settings.master.gender_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.GenderSettings)
  })
_sym_db.RegisterMessage(GenderSettings)


# @@protoc_insertion_point(module_scope)
