# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/iap_item_category_display.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import iap_item_category_pb2 as pogoprotos_dot_enums_dot_iap__item__category__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/iap_item_category_display.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n:pogoprotos/settings/master/iap_item_category_display.proto\x12\x1apogoprotos.settings.master\x1a(pogoprotos/enums/iap_item_category.proto\"\xd9\x01\n\x16IapItemCategoryDisplay\x12\x37\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32%.pogoprotos.enums.HoloIapItemCategory\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06hidden\x18\x03 \x01(\x08\x12\x12\n\nsort_order\x18\x04 \x01(\x05\x12\x16\n\x0e\x62\x61nner_enabled\x18\x05 \x01(\x08\x12\x14\n\x0c\x62\x61nner_title\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\tb\x06proto3'
  ,
  dependencies=[pogoprotos_dot_enums_dot_iap__item__category__pb2.DESCRIPTOR,])




_IAPITEMCATEGORYDISPLAY = _descriptor.Descriptor(
  name='IapItemCategoryDisplay',
  full_name='pogoprotos.settings.master.IapItemCategoryDisplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.category', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hidden', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.hidden', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_order', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.sort_order', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_enabled', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.banner_enabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='banner_title', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.banner_title', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_url', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.image_url', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='pogoprotos.settings.master.IapItemCategoryDisplay.description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=350,
)

_IAPITEMCATEGORYDISPLAY.fields_by_name['category'].enum_type = pogoprotos_dot_enums_dot_iap__item__category__pb2._HOLOIAPITEMCATEGORY
DESCRIPTOR.message_types_by_name['IapItemCategoryDisplay'] = _IAPITEMCATEGORYDISPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IapItemCategoryDisplay = _reflection.GeneratedProtocolMessageType('IapItemCategoryDisplay', (_message.Message,), {
  'DESCRIPTOR' : _IAPITEMCATEGORYDISPLAY,
  '__module__' : 'pogoprotos.settings.master.iap_item_category_display_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.IapItemCategoryDisplay)
  })
_sym_db.RegisterMessage(IapItemCategoryDisplay)


# @@protoc_insertion_point(module_scope)
