# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gamepoi/messages/submit_poi_text_metadata_update_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gamepoi/messages/submit_poi_text_metadata_update_message.proto',
  package='pogoprotos.networking.game.gamepoi.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nYpogoprotos/networking/game/gamepoi/messages/submit_poi_text_metadata_update_message.proto\x12+pogoprotos.networking.game.gamepoi.messages\"X\n\"SubmitPoiTextMetadataUpdateMessage\x12\x0e\n\x06poi_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tb\x06proto3'
)




_SUBMITPOITEXTMETADATAUPDATEMESSAGE = _descriptor.Descriptor(
  name='SubmitPoiTextMetadataUpdateMessage',
  full_name='pogoprotos.networking.game.gamepoi.messages.SubmitPoiTextMetadataUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poi_id', full_name='pogoprotos.networking.game.gamepoi.messages.SubmitPoiTextMetadataUpdateMessage.poi_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='pogoprotos.networking.game.gamepoi.messages.SubmitPoiTextMetadataUpdateMessage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='pogoprotos.networking.game.gamepoi.messages.SubmitPoiTextMetadataUpdateMessage.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['SubmitPoiTextMetadataUpdateMessage'] = _SUBMITPOITEXTMETADATAUPDATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitPoiTextMetadataUpdateMessage = _reflection.GeneratedProtocolMessageType('SubmitPoiTextMetadataUpdateMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITPOITEXTMETADATAUPDATEMESSAGE,
  '__module__' : 'pogoprotos.networking.game.gamepoi.messages.submit_poi_text_metadata_update_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.game.gamepoi.messages.SubmitPoiTextMetadataUpdateMessage)
  })
_sym_db.RegisterMessage(SubmitPoiTextMetadataUpdateMessage)


# @@protoc_insertion_point(module_scope)
