# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/assetcache/journal_version.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/assetcache/journal_version.proto',
  package='pogoprotos.data.assetcache',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n0pogoprotos/data/assetcache/journal_version.proto\x12\x1apogoprotos.data.assetcache\"!\n\x0eJournalVersion\x12\x0f\n\x07version\x18\x01 \x01(\x05\x62\x06proto3'
)




_JOURNALVERSION = _descriptor.Descriptor(
  name='JournalVersion',
  full_name='pogoprotos.data.assetcache.JournalVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='pogoprotos.data.assetcache.JournalVersion.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['JournalVersion'] = _JOURNALVERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JournalVersion = _reflection.GeneratedProtocolMessageType('JournalVersion', (_message.Message,), {
  'DESCRIPTOR' : _JOURNALVERSION,
  '__module__' : 'pogoprotos.data.assetcache.journal_version_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.assetcache.JournalVersion)
  })
_sym_db.RegisterMessage(JournalVersion)


# @@protoc_insertion_point(module_scope)
