# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gameanticheat/game_anticheat_action.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gameanticheat/game_anticheat_action.proto',
  package='pogoprotos.networking.game.gameanticheat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nDpogoprotos/networking/game/gameanticheat/game_anticheat_action.proto\x12(pogoprotos.networking.game.gameanticheat*t\n\x13GameAnticheatAction\x12!\n\x1dUNKNOWN_GAME_ANTICHEAT_ACTION\x10\x00\x12\x1e\n\x18GET_OUTSTANDING_WARNINGS\x10\xc0\x9a\x0c\x12\x1a\n\x14\x41\x43KNOWLEDGE_WARNINGS\x10\xc1\x9a\x0c\x62\x06proto3'
)

_GAMEANTICHEATACTION = _descriptor.EnumDescriptor(
  name='GameAnticheatAction',
  full_name='pogoprotos.networking.game.gameanticheat.GameAnticheatAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_GAME_ANTICHEAT_ACTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_OUTSTANDING_WARNINGS', index=1, number=200000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACKNOWLEDGE_WARNINGS', index=2, number=200001,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=114,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_GAMEANTICHEATACTION)

GameAnticheatAction = enum_type_wrapper.EnumTypeWrapper(_GAMEANTICHEATACTION)
UNKNOWN_GAME_ANTICHEAT_ACTION = 0
GET_OUTSTANDING_WARNINGS = 200000
ACKNOWLEDGE_WARNINGS = 200001


DESCRIPTOR.enum_types_by_name['GameAnticheatAction'] = _GAMEANTICHEATACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
