# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/confirm_trading_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.trading import trading_pb2 as pogoprotos_dot_data_dot_trading_dot_trading__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/confirm_trading_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n>pogoprotos/networking/responses/confirm_trading_response.proto\x12\x1fpogoprotos.networking.responses\x1a%pogoprotos/data/trading/trading.proto\"\xcb\x04\n\x16\x43onfirmTradingResponse\x12N\n\x06result\x18\x01 \x01(\x0e\x32>.pogoprotos.networking.responses.ConfirmTradingResponse.Result\x12\x31\n\x07trading\x18\x02 \x01(\x0b\x32 .pogoprotos.data.trading.Trading\"\xad\x03\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x12\x1a\n\x16\x45RROR_FRIEND_NOT_FOUND\x10\x03\x12\x1b\n\x17\x45RROR_INVALID_PLAYER_ID\x10\x04\x12\x17\n\x13\x45RROR_INVALID_STATE\x10\x05\x12\x17\n\x13\x45RROR_STATE_HANDLER\x10\x06\x12\x19\n\x15\x45RROR_INVALID_POKEMON\x10\x07\x12\x1e\n\x1a\x45RROR_INSUFFICIENT_PAYMENT\x10\x08\x12\x1b\n\x17\x45RROR_NO_PLAYER_POKEMON\x10\t\x12\x1b\n\x17\x45RROR_NO_FRIEND_POKEMON\x10\n\x12\"\n\x1e\x45RROR_PLAYER_ALREADY_CONFIRMED\x10\x0b\x12#\n\x1f\x45RROR_TRANSACTION_LOG_NOT_MATCH\x10\x0c\x12\x19\n\x15\x45RROR_TRADING_EXPIRED\x10\r\x12\x15\n\x11\x45RROR_TRANSACTION\x10\x0e\x12\x1d\n\x19\x45RROR_DAILY_LIMIT_REACHED\x10\x0f\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_trading_dot_trading__pb2.DESCRIPTOR,])



_CONFIRMTRADINGRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.ConfirmTradingResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_FRIEND_NOT_FOUND', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_PLAYER_ID', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_STATE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_STATE_HANDLER', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_POKEMON', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INSUFFICIENT_PAYMENT', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_PLAYER_POKEMON', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_FRIEND_POKEMON', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PLAYER_ALREADY_CONFIRMED', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_TRANSACTION_LOG_NOT_MATCH', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_TRADING_EXPIRED', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_TRANSACTION', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DAILY_LIMIT_REACHED', index=15, number=15,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=297,
  serialized_end=726,
)
_sym_db.RegisterEnumDescriptor(_CONFIRMTRADINGRESPONSE_RESULT)


_CONFIRMTRADINGRESPONSE = _descriptor.Descriptor(
  name='ConfirmTradingResponse',
  full_name='pogoprotos.networking.responses.ConfirmTradingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.ConfirmTradingResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trading', full_name='pogoprotos.networking.responses.ConfirmTradingResponse.trading', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIRMTRADINGRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=726,
)

_CONFIRMTRADINGRESPONSE.fields_by_name['result'].enum_type = _CONFIRMTRADINGRESPONSE_RESULT
_CONFIRMTRADINGRESPONSE.fields_by_name['trading'].message_type = pogoprotos_dot_data_dot_trading_dot_trading__pb2._TRADING
_CONFIRMTRADINGRESPONSE_RESULT.containing_type = _CONFIRMTRADINGRESPONSE
DESCRIPTOR.message_types_by_name['ConfirmTradingResponse'] = _CONFIRMTRADINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfirmTradingResponse = _reflection.GeneratedProtocolMessageType('ConfirmTradingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMTRADINGRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.confirm_trading_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.ConfirmTradingResponse)
  })
_sym_db.RegisterMessage(ConfirmTradingResponse)


# @@protoc_insertion_point(module_scope)
