# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_player_profile_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.badge import awarded_gym_badge_pb2 as pogoprotos_dot_data_dot_badge_dot_awarded__gym__badge__pb2
from pogoprotos.enums import badge_type_pb2 as pogoprotos_dot_enums_dot_badge__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/get_player_profile_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nApogoprotos/networking/responses/get_player_profile_response.proto\x12\x1fpogoprotos.networking.responses\x1a-pogoprotos/data/badge/awarded_gym_badge.proto\x1a!pogoprotos/enums/badge_type.proto\"\xb7\x04\n\x18GetPlayerProfileResponse\x12P\n\x06result\x18\x01 \x01(\x0e\x32@.pogoprotos.networking.responses.GetPlayerProfileResponse.Result\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12U\n\x06\x62\x61\x64ges\x18\x03 \x03(\x0b\x32\x45.pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge\x12W\n\ngym_badges\x18\x04 \x01(\x0b\x32\x43.pogoprotos.networking.responses.GetPlayerProfileResponse.GymBadges\x1aU\n\tGymBadges\x12\x39\n\tgym_badge\x18\x01 \x03(\x0b\x32&.pogoprotos.data.badge.AwardedGymBadge\x12\r\n\x05total\x18\x02 \x01(\x05\x1a\x8b\x01\n\x0bPlayerBadge\x12/\n\nbadge_type\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.BadgeType\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x13\n\x0bstart_value\x18\x03 \x01(\x05\x12\x11\n\tend_value\x18\x04 \x01(\x05\x12\x15\n\rcurrent_value\x18\x05 \x01(\x01\" \n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_badge_dot_awarded__gym__badge__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_badge__type__pb2.DESCRIPTOR,])



_GETPLAYERPROFILERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=720,
  serialized_end=752,
)
_sym_db.RegisterEnumDescriptor(_GETPLAYERPROFILERESPONSE_RESULT)


_GETPLAYERPROFILERESPONSE_GYMBADGES = _descriptor.Descriptor(
  name='GymBadges',
  full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.GymBadges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gym_badge', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.GymBadges.gym_badge', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.GymBadges.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=576,
)

_GETPLAYERPROFILERESPONSE_PLAYERBADGE = _descriptor.Descriptor(
  name='PlayerBadge',
  full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='badge_type', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge.badge_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge.rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_value', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge.start_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_value', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge.end_value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_value', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge.current_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=718,
)

_GETPLAYERPROFILERESPONSE = _descriptor.Descriptor(
  name='GetPlayerProfileResponse',
  full_name='pogoprotos.networking.responses.GetPlayerProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='badges', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.badges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gym_badges', full_name='pogoprotos.networking.responses.GetPlayerProfileResponse.gym_badges', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETPLAYERPROFILERESPONSE_GYMBADGES, _GETPLAYERPROFILERESPONSE_PLAYERBADGE, ],
  enum_types=[
    _GETPLAYERPROFILERESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=752,
)

_GETPLAYERPROFILERESPONSE_GYMBADGES.fields_by_name['gym_badge'].message_type = pogoprotos_dot_data_dot_badge_dot_awarded__gym__badge__pb2._AWARDEDGYMBADGE
_GETPLAYERPROFILERESPONSE_GYMBADGES.containing_type = _GETPLAYERPROFILERESPONSE
_GETPLAYERPROFILERESPONSE_PLAYERBADGE.fields_by_name['badge_type'].enum_type = pogoprotos_dot_enums_dot_badge__type__pb2._BADGETYPE
_GETPLAYERPROFILERESPONSE_PLAYERBADGE.containing_type = _GETPLAYERPROFILERESPONSE
_GETPLAYERPROFILERESPONSE.fields_by_name['result'].enum_type = _GETPLAYERPROFILERESPONSE_RESULT
_GETPLAYERPROFILERESPONSE.fields_by_name['badges'].message_type = _GETPLAYERPROFILERESPONSE_PLAYERBADGE
_GETPLAYERPROFILERESPONSE.fields_by_name['gym_badges'].message_type = _GETPLAYERPROFILERESPONSE_GYMBADGES
_GETPLAYERPROFILERESPONSE_RESULT.containing_type = _GETPLAYERPROFILERESPONSE
DESCRIPTOR.message_types_by_name['GetPlayerProfileResponse'] = _GETPLAYERPROFILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPlayerProfileResponse = _reflection.GeneratedProtocolMessageType('GetPlayerProfileResponse', (_message.Message,), {

  'GymBadges' : _reflection.GeneratedProtocolMessageType('GymBadges', (_message.Message,), {
    'DESCRIPTOR' : _GETPLAYERPROFILERESPONSE_GYMBADGES,
    '__module__' : 'pogoprotos.networking.responses.get_player_profile_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GetPlayerProfileResponse.GymBadges)
    })
  ,

  'PlayerBadge' : _reflection.GeneratedProtocolMessageType('PlayerBadge', (_message.Message,), {
    'DESCRIPTOR' : _GETPLAYERPROFILERESPONSE_PLAYERBADGE,
    '__module__' : 'pogoprotos.networking.responses.get_player_profile_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GetPlayerProfileResponse.PlayerBadge)
    })
  ,
  'DESCRIPTOR' : _GETPLAYERPROFILERESPONSE,
  '__module__' : 'pogoprotos.networking.responses.get_player_profile_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GetPlayerProfileResponse)
  })
_sym_db.RegisterMessage(GetPlayerProfileResponse)
_sym_db.RegisterMessage(GetPlayerProfileResponse.GymBadges)
_sym_db.RegisterMessage(GetPlayerProfileResponse.PlayerBadge)


# @@protoc_insertion_point(module_scope)
