# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/get_tutorial_egg_action_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/get_tutorial_egg_action_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nFpogoprotos/networking/responses/get_tutorial_egg_action_response.proto\x12\x1fpogoprotos.networking.responses\"\xf5\x01\n\x1cGetTutorialEggActionResponse\x12T\n\x06result\x18\x01 \x01(\x0e\x32\x44.pogoprotos.networking.responses.GetTutorialEggActionResponse.Result\"\x7f\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12)\n%ERROR_PLAYER_ALREADY_HAS_TUTORIAL_EGG\x10\x02\x12\x1b\n\x17\x45RROR_FAILED_TO_ADD_EGG\x10\x03\x12\x15\n\x11\x45RROR_NOT_V2_FLOW\x10\x04\x62\x06proto3'
)



_GETTUTORIALEGGACTIONRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.GetTutorialEggActionResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PLAYER_ALREADY_HAS_TUTORIAL_EGG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_FAILED_TO_ADD_EGG', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NOT_V2_FLOW', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=226,
  serialized_end=353,
)
_sym_db.RegisterEnumDescriptor(_GETTUTORIALEGGACTIONRESPONSE_RESULT)


_GETTUTORIALEGGACTIONRESPONSE = _descriptor.Descriptor(
  name='GetTutorialEggActionResponse',
  full_name='pogoprotos.networking.responses.GetTutorialEggActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.GetTutorialEggActionResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETTUTORIALEGGACTIONRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=353,
)

_GETTUTORIALEGGACTIONRESPONSE.fields_by_name['result'].enum_type = _GETTUTORIALEGGACTIONRESPONSE_RESULT
_GETTUTORIALEGGACTIONRESPONSE_RESULT.containing_type = _GETTUTORIALEGGACTIONRESPONSE
DESCRIPTOR.message_types_by_name['GetTutorialEggActionResponse'] = _GETTUTORIALEGGACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTutorialEggActionResponse = _reflection.GeneratedProtocolMessageType('GetTutorialEggActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTUTORIALEGGACTIONRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.get_tutorial_egg_action_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.GetTutorialEggActionResponse)
  })
_sym_db.RegisterMessage(GetTutorialEggActionResponse)


# @@protoc_insertion_point(module_scope)
