# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/remove_quest_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/remove_quest_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n;pogoprotos/networking/responses/remove_quest_response.proto\x12\x1fpogoprotos.networking.responses\"\xc4\x01\n\x13RemoveQuestResponse\x12K\n\x06status\x18\x01 \x01(\x0e\x32;.pogoprotos.networking.responses.RemoveQuestResponse.Status\"`\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x19\n\x15\x45RROR_QUEST_NOT_FOUND\x10\x02\x12#\n\x1f\x45RROR_STORY_QUEST_NOT_REMOVABLE\x10\x03\x62\x06proto3'
)



_REMOVEQUESTRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.responses.RemoveQuestResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_QUEST_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_STORY_QUEST_NOT_REMOVABLE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=197,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_REMOVEQUESTRESPONSE_STATUS)


_REMOVEQUESTRESPONSE = _descriptor.Descriptor(
  name='RemoveQuestResponse',
  full_name='pogoprotos.networking.responses.RemoveQuestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.responses.RemoveQuestResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REMOVEQUESTRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=293,
)

_REMOVEQUESTRESPONSE.fields_by_name['status'].enum_type = _REMOVEQUESTRESPONSE_STATUS
_REMOVEQUESTRESPONSE_STATUS.containing_type = _REMOVEQUESTRESPONSE
DESCRIPTOR.message_types_by_name['RemoveQuestResponse'] = _REMOVEQUESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoveQuestResponse = _reflection.GeneratedProtocolMessageType('RemoveQuestResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEQUESTRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.remove_quest_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.RemoveQuestResponse)
  })
_sym_db.RegisterMessage(RemoveQuestResponse)


# @@protoc_insertion_point(module_scope)
