# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/save_social_player_settings_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/save_social_player_settings_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nJpogoprotos/networking/responses/save_social_player_settings_response.proto\x12\x1fpogoprotos.networking.responses\"\xb1\x01\n SaveSocialPlayerSettingsResponse\x12X\n\x06result\x18\x01 \x01(\x0e\x32H.pogoprotos.networking.responses.SaveSocialPlayerSettingsResponse.Result\"3\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x11\n\rERROR_UNKNOWN\x10\x02\x62\x06proto3'
)



_SAVESOCIALPLAYERSETTINGSRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.SaveSocialPlayerSettingsResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=238,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_SAVESOCIALPLAYERSETTINGSRESPONSE_RESULT)


_SAVESOCIALPLAYERSETTINGSRESPONSE = _descriptor.Descriptor(
  name='SaveSocialPlayerSettingsResponse',
  full_name='pogoprotos.networking.responses.SaveSocialPlayerSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.SaveSocialPlayerSettingsResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAVESOCIALPLAYERSETTINGSRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=289,
)

_SAVESOCIALPLAYERSETTINGSRESPONSE.fields_by_name['result'].enum_type = _SAVESOCIALPLAYERSETTINGSRESPONSE_RESULT
_SAVESOCIALPLAYERSETTINGSRESPONSE_RESULT.containing_type = _SAVESOCIALPLAYERSETTINGSRESPONSE
DESCRIPTOR.message_types_by_name['SaveSocialPlayerSettingsResponse'] = _SAVESOCIALPLAYERSETTINGSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveSocialPlayerSettingsResponse = _reflection.GeneratedProtocolMessageType('SaveSocialPlayerSettingsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVESOCIALPLAYERSETTINGSRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.save_social_player_settings_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.SaveSocialPlayerSettingsResponse)
  })
_sym_db.RegisterMessage(SaveSocialPlayerSettingsResponse)


# @@protoc_insertion_point(module_scope)
