# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/save_player_snapshot_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/save_player_snapshot_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nCpogoprotos/networking/responses/save_player_snapshot_response.proto\x12\x1fpogoprotos.networking.responses\"\xe3\x01\n\x1aSavePlayerSnapshotResponse\x12R\n\x06result\x18\x01 \x01(\x0e\x32\x42.pogoprotos.networking.responses.SavePlayerSnapshotResponse.Result\"q\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x16\n\x12TOO_SOON_TO_UPDATE\x10\x02\x12\x1a\n\x16\x45RROR_FAILED_TO_UPDATE\x10\x03\x12\x1b\n\x17\x45RROR_REQUEST_TIMED_OUT\x10\x04\x62\x06proto3'
)



_SAVEPLAYERSNAPSHOTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.SavePlayerSnapshotResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_SOON_TO_UPDATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_FAILED_TO_UPDATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_REQUEST_TIMED_OUT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=332,
)
_sym_db.RegisterEnumDescriptor(_SAVEPLAYERSNAPSHOTRESPONSE_RESULT)


_SAVEPLAYERSNAPSHOTRESPONSE = _descriptor.Descriptor(
  name='SavePlayerSnapshotResponse',
  full_name='pogoprotos.networking.responses.SavePlayerSnapshotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.SavePlayerSnapshotResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAVEPLAYERSNAPSHOTRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=332,
)

_SAVEPLAYERSNAPSHOTRESPONSE.fields_by_name['result'].enum_type = _SAVEPLAYERSNAPSHOTRESPONSE_RESULT
_SAVEPLAYERSNAPSHOTRESPONSE_RESULT.containing_type = _SAVEPLAYERSNAPSHOTRESPONSE
DESCRIPTOR.message_types_by_name['SavePlayerSnapshotResponse'] = _SAVEPLAYERSNAPSHOTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SavePlayerSnapshotResponse = _reflection.GeneratedProtocolMessageType('SavePlayerSnapshotResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVEPLAYERSNAPSHOTRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.save_player_snapshot_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.SavePlayerSnapshotResponse)
  })
_sym_db.RegisterMessage(SavePlayerSnapshotResponse)


# @@protoc_insertion_point(module_scope)
