# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/set_lobby_pokemon_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.raid import lobby_pb2 as pogoprotos_dot_data_dot_raid_dot_lobby__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/set_lobby_pokemon_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n@pogoprotos/networking/responses/set_lobby_pokemon_response.proto\x12\x1fpogoprotos.networking.responses\x1a pogoprotos/data/raid/lobby.proto\"\x8a\x02\n\x17SetLobbyPokemonResponse\x12O\n\x06result\x18\x01 \x01(\x0e\x32?.pogoprotos.networking.responses.SetLobbyPokemonResponse.Result\x12*\n\x05lobby\x18\x02 \x01(\x0b\x32\x1b.pogoprotos.data.raid.Lobby\"r\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x19\n\x15\x45RROR_LOBBY_NOT_FOUND\x10\x02\x12\x1a\n\x16\x45RROR_RAID_UNAVAILABLE\x10\x03\x12\x19\n\x15\x45RROR_INVALID_POKEMON\x10\x04\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_raid_dot_lobby__pb2.DESCRIPTOR,])



_SETLOBBYPOKEMONRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pogoprotos.networking.responses.SetLobbyPokemonResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_LOBBY_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_RAID_UNAVAILABLE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_POKEMON', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=288,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_SETLOBBYPOKEMONRESPONSE_RESULT)


_SETLOBBYPOKEMONRESPONSE = _descriptor.Descriptor(
  name='SetLobbyPokemonResponse',
  full_name='pogoprotos.networking.responses.SetLobbyPokemonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='pogoprotos.networking.responses.SetLobbyPokemonResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lobby', full_name='pogoprotos.networking.responses.SetLobbyPokemonResponse.lobby', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETLOBBYPOKEMONRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=402,
)

_SETLOBBYPOKEMONRESPONSE.fields_by_name['result'].enum_type = _SETLOBBYPOKEMONRESPONSE_RESULT
_SETLOBBYPOKEMONRESPONSE.fields_by_name['lobby'].message_type = pogoprotos_dot_data_dot_raid_dot_lobby__pb2._LOBBY
_SETLOBBYPOKEMONRESPONSE_RESULT.containing_type = _SETLOBBYPOKEMONRESPONSE
DESCRIPTOR.message_types_by_name['SetLobbyPokemonResponse'] = _SETLOBBYPOKEMONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetLobbyPokemonResponse = _reflection.GeneratedProtocolMessageType('SetLobbyPokemonResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETLOBBYPOKEMONRESPONSE,
  '__module__' : 'pogoprotos.networking.responses.set_lobby_pokemon_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.SetLobbyPokemonResponse)
  })
_sym_db.RegisterMessage(SetLobbyPokemonResponse)


# @@protoc_insertion_point(module_scope)
