# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gamepoi/responses/submit_poi_image_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gamepoi/responses/submit_poi_image_response.proto',
  package='pogoprotos.networking.game.gamepoi.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nLpogoprotos/networking/game/gamepoi/responses/submit_poi_image_response.proto\x12,pogoprotos.networking.game.gamepoi.responses\"\x9e\x02\n\x16SubmitPoiImageResponse\x12[\n\x06status\x18\x01 \x01(\x0e\x32K.pogoprotos.networking.game.gamepoi.responses.SubmitPoiImageResponse.Status\"\xa6\x01\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x12\x1f\n\x1bTOO_MANY_RECENT_SUBMISSIONS\x10\x03\x12\t\n\x05MINOR\x10\x04\x12\x11\n\rNOT_AVAILABLE\x10\x05\x12\x11\n\rMISSING_IMAGE\x10\x06\x12\x11\n\rINVALID_INPUT\x10\x07\x62\x06proto3'
)



_SUBMITPOIIMAGERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pogoprotos.networking.game.gamepoi.responses.SubmitPoiImageResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOO_MANY_RECENT_SUBMISSIONS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MINOR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_AVAILABLE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_IMAGE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_INPUT', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=247,
  serialized_end=413,
)
_sym_db.RegisterEnumDescriptor(_SUBMITPOIIMAGERESPONSE_STATUS)


_SUBMITPOIIMAGERESPONSE = _descriptor.Descriptor(
  name='SubmitPoiImageResponse',
  full_name='pogoprotos.networking.game.gamepoi.responses.SubmitPoiImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pogoprotos.networking.game.gamepoi.responses.SubmitPoiImageResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBMITPOIIMAGERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=413,
)

_SUBMITPOIIMAGERESPONSE.fields_by_name['status'].enum_type = _SUBMITPOIIMAGERESPONSE_STATUS
_SUBMITPOIIMAGERESPONSE_STATUS.containing_type = _SUBMITPOIIMAGERESPONSE
DESCRIPTOR.message_types_by_name['SubmitPoiImageResponse'] = _SUBMITPOIIMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitPoiImageResponse = _reflection.GeneratedProtocolMessageType('SubmitPoiImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITPOIIMAGERESPONSE,
  '__module__' : 'pogoprotos.networking.game.gamepoi.responses.submit_poi_image_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.game.gamepoi.responses.SubmitPoiImageResponse)
  })
_sym_db.RegisterMessage(SubmitPoiImageResponse)


# @@protoc_insertion_point(module_scope)
