# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto',
  package='pogoprotos.networking.game.gamepoi.responses',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n^pogoprotos/networking/game/gamepoi/responses/submit_sponsor_poi_location_update_response.proto\x12,pogoprotos.networking.game.gamepoi.responses\"(\n&SubmitSponsorPoiLocationUpdateResponseb\x06proto3'
)




_SUBMITSPONSORPOILOCATIONUPDATERESPONSE = _descriptor.Descriptor(
  name='SubmitSponsorPoiLocationUpdateResponse',
  full_name='pogoprotos.networking.game.gamepoi.responses.SubmitSponsorPoiLocationUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['SubmitSponsorPoiLocationUpdateResponse'] = _SUBMITSPONSORPOILOCATIONUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitSponsorPoiLocationUpdateResponse = _reflection.GeneratedProtocolMessageType('SubmitSponsorPoiLocationUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITSPONSORPOILOCATIONUPDATERESPONSE,
  '__module__' : 'pogoprotos.networking.game.gamepoi.responses.submit_sponsor_poi_location_update_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.game.gamepoi.responses.SubmitSponsorPoiLocationUpdateResponse)
  })
_sym_db.RegisterMessage(SubmitSponsorPoiLocationUpdateResponse)


# @@protoc_insertion_point(module_scope)
