# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/game/gameping/game_ping_action.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/game/gameping/game_ping_action.proto',
  package='pogoprotos.networking.game.gameping',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n:pogoprotos/networking/game/gameping/game_ping_action.proto\x12#pogoprotos.networking.game.gameping*c\n\x0eGamePingAction\x12\x1c\n\x18UNKNOWN_GAME_PING_ACTION\x10\x00\x12\n\n\x04PING\x10\xe0\xb6\r\x12\x10\n\nPING_ASYNC\x10\xe1\xb6\r\x12\x15\n\x0fPING_DOWNSTREAM\x10\xe2\xb6\rb\x06proto3'
)

_GAMEPINGACTION = _descriptor.EnumDescriptor(
  name='GamePingAction',
  full_name='pogoprotos.networking.game.gameping.GamePingAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_GAME_PING_ACTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING', index=1, number=220000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING_ASYNC', index=2, number=220001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING_DOWNSTREAM', index=3, number=220002,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=99,
  serialized_end=198,
)
_sym_db.RegisterEnumDescriptor(_GAMEPINGACTION)

GamePingAction = enum_type_wrapper.EnumTypeWrapper(_GAMEPINGACTION)
UNKNOWN_GAME_PING_ACTION = 0
PING = 220000
PING_ASYNC = 220001
PING_DOWNSTREAM = 220002


DESCRIPTOR.enum_types_by_name['GamePingAction'] = _GAMEPINGACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
