# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/get_client_bgmode_settings_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/requests/get_client_bgmode_settings_message.proto',
  package='pogoprotos.networking.platform.requests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nPpogoprotos/networking/platform/requests/get_client_bgmode_settings_message.proto\x12\'pogoprotos.networking.platform.requests\" \n\x1eGetClientBgmodeSettingsMessageb\x06proto3'
)




_GETCLIENTBGMODESETTINGSMESSAGE = _descriptor.Descriptor(
  name='GetClientBgmodeSettingsMessage',
  full_name='pogoprotos.networking.platform.requests.GetClientBgmodeSettingsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['GetClientBgmodeSettingsMessage'] = _GETCLIENTBGMODESETTINGSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetClientBgmodeSettingsMessage = _reflection.GeneratedProtocolMessageType('GetClientBgmodeSettingsMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETCLIENTBGMODESETTINGSMESSAGE,
  '__module__' : 'pogoprotos.networking.platform.requests.get_client_bgmode_settings_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.requests.GetClientBgmodeSettingsMessage)
  })
_sym_db.RegisterMessage(GetClientBgmodeSettingsMessage)


# @@protoc_insertion_point(module_scope)
