# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/platform/requests/list_login_action_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/platform/requests/list_login_action_message.proto',
  package='pogoprotos.networking.platform.requests',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nGpogoprotos/networking/platform/requests/list_login_action_message.proto\x12\'pogoprotos.networking.platform.requests\"\x18\n\x16ListLoginActionMessageb\x06proto3'
)




_LISTLOGINACTIONMESSAGE = _descriptor.Descriptor(
  name='ListLoginActionMessage',
  full_name='pogoprotos.networking.platform.requests.ListLoginActionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['ListLoginActionMessage'] = _LISTLOGINACTIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListLoginActionMessage = _reflection.GeneratedProtocolMessageType('ListLoginActionMessage', (_message.Message,), {
  'DESCRIPTOR' : _LISTLOGINACTIONMESSAGE,
  '__module__' : 'pogoprotos.networking.platform.requests.list_login_action_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.platform.requests.ListLoginActionMessage)
  })
_sym_db.RegisterMessage(ListLoginActionMessage)


# @@protoc_insertion_point(module_scope)
