from . import test_area
from . import test_auth
from . import test_device
from . import test_devicesetting
from . import test_geofences
from . import test_monlist
from . import test_routecalc
from . import test_walker
from . import test_walkerarea
