from . import test_area  # noqa: F401
from . import test_auth  # noqa: F401
from . import test_device  # noqa: F401
from . import test_devicesetting  # noqa: F401
from . import test_geofences  # noqa: F401
from . import test_monlist  # noqa: F401
from . import test_pogoauth  # noqa: F401
from . import test_routecalc  # noqa: F401
from . import test_walker  # noqa: F401
from . import test_walkerarea  # noqa: F401
