# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/titan/messages/submit_new_poi_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/titan/messages/submit_new_poi_message.proto',
  package='pogoprotos.networking.titan.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nApogoprotos/networking/titan/messages/submit_new_poi_message.proto\x12$pogoprotos.networking.titan.messages\"\x97\x01\n\x13SubmitNewPoiMessage\x12\r\n\x05title\x18\x01 \x01(\t\x12\x18\n\x10long_description\x18\x02 \x01(\t\x12\x0e\n\x06lat_e6\x18\x04 \x01(\x05\x12\x0e\n\x06lng_e6\x18\x05 \x01(\x05\x12\x1c\n\x14supporting_statement\x18\x0e \x01(\t\x12\x19\n\x11\x61sync_file_upload\x18\x12 \x01(\x08\x62\x06proto3'
)




_SUBMITNEWPOIMESSAGE = _descriptor.Descriptor(
  name='SubmitNewPoiMessage',
  full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='long_description', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.long_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lat_e6', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.lat_e6', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lng_e6', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.lng_e6', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supporting_statement', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.supporting_statement', index=4,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='async_file_upload', full_name='pogoprotos.networking.titan.messages.SubmitNewPoiMessage.async_file_upload', index=5,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=259,
)

DESCRIPTOR.message_types_by_name['SubmitNewPoiMessage'] = _SUBMITNEWPOIMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitNewPoiMessage = _reflection.GeneratedProtocolMessageType('SubmitNewPoiMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITNEWPOIMESSAGE,
  '__module__' : 'pogoprotos.networking.titan.messages.submit_new_poi_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.titan.messages.SubmitNewPoiMessage)
  })
_sym_db.RegisterMessage(SubmitNewPoiMessage)


# @@protoc_insertion_point(module_scope)
