# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/titan/messages/submit_new_route_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.route import route_checkpoint_pb2 as pogoprotos_dot_data_dot_route_dot_route__checkpoint__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/titan/messages/submit_new_route_message.proto',
  package='pogoprotos.networking.titan.messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\nCpogoprotos/networking/titan/messages/submit_new_route_message.proto\x12$pogoprotos.networking.titan.messages\x1a,pogoprotos/data/route/route_checkpoint.proto\"\xa1\x03\n\x15SubmitNewRouteMessage\x12\x1b\n\x13route_submission_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12`\n\x0bvisit_order\x18\x05 \x01(\x0e\x32K.pogoprotos.networking.titan.messages.SubmitNewRouteMessage.RouteVisitOrder\x12;\n\x0b\x63heckpoints\x18\x06 \x03(\x0b\x32&.pogoprotos.data.route.RouteCheckpoint\x12\x45\n\nmain_image\x18\x07 \x01(\x0b\x32\x31.pogoprotos.data.route.RouteCheckpoint.RouteImage\"a\n\x0fRouteVisitOrder\x12!\n\x1dROUTE_VISIT_ORDER_UNSPECIFIED\x10\x00\x12\x0c\n\x08IN_ORDER\x10\x01\x12\r\n\tUNORDERED\x10\x02\x12\x0e\n\nREVERSIBLE\x10\x03\x62\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_route_dot_route__checkpoint__pb2.DESCRIPTOR,])



_SUBMITNEWROUTEMESSAGE_ROUTEVISITORDER = _descriptor.EnumDescriptor(
  name='RouteVisitOrder',
  full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.RouteVisitOrder',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROUTE_VISIT_ORDER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_ORDER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNORDERED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSIBLE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=476,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_SUBMITNEWROUTEMESSAGE_ROUTEVISITORDER)


_SUBMITNEWROUTEMESSAGE = _descriptor.Descriptor(
  name='SubmitNewRouteMessage',
  full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='route_submission_id', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.route_submission_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visit_order', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.visit_order', index=3,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoints', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.checkpoints', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='main_image', full_name='pogoprotos.networking.titan.messages.SubmitNewRouteMessage.main_image', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBMITNEWROUTEMESSAGE_ROUTEVISITORDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=573,
)

_SUBMITNEWROUTEMESSAGE.fields_by_name['visit_order'].enum_type = _SUBMITNEWROUTEMESSAGE_ROUTEVISITORDER
_SUBMITNEWROUTEMESSAGE.fields_by_name['checkpoints'].message_type = pogoprotos_dot_data_dot_route_dot_route__checkpoint__pb2._ROUTECHECKPOINT
_SUBMITNEWROUTEMESSAGE.fields_by_name['main_image'].message_type = pogoprotos_dot_data_dot_route_dot_route__checkpoint__pb2._ROUTECHECKPOINT_ROUTEIMAGE
_SUBMITNEWROUTEMESSAGE_ROUTEVISITORDER.containing_type = _SUBMITNEWROUTEMESSAGE
DESCRIPTOR.message_types_by_name['SubmitNewRouteMessage'] = _SUBMITNEWROUTEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitNewRouteMessage = _reflection.GeneratedProtocolMessageType('SubmitNewRouteMessage', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITNEWROUTEMESSAGE,
  '__module__' : 'pogoprotos.networking.titan.messages.submit_new_route_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.titan.messages.SubmitNewRouteMessage)
  })
_sym_db.RegisterMessage(SubmitNewRouteMessage)


# @@protoc_insertion_point(module_scope)
