# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/data/combat/combat_log.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.combat import combat_season_result_pb2 as pogoprotos_dot_data_dot_combat_dot_combat__season__result__pb2
from pogoprotos.data.vsseeker import vs_seeker_battle_result_pb2 as pogoprotos_dot_data_dot_vsseeker_dot_vs__seeker__battle__result__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/data/combat/combat_log.proto',
  package='pogoprotos.data.combat',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\'pogoprotos/data/combat/combat_log.proto\x12\x16pogoprotos.data.combat\x1a\x31pogoprotos/data/combat/combat_season_result.proto\x1a\x36pogoprotos/data/vsseeker/vs_seeker_battle_result.proto\"\xc1\x02\n\tCombatLog\x12\x44\n\x10lifetime_results\x18\x01 \x01(\x0b\x32*.pogoprotos.data.combat.CombatSeasonResult\x12J\n\x16\x63urrent_season_results\x18\x02 \x01(\x0b\x32*.pogoprotos.data.combat.CombatSeasonResult\x12U\n\x1d\x63urrent_vs_seeker_set_results\x18\x04 \x03(\x0b\x32..pogoprotos.data.vsseeker.VsSeekerBattleResult\x12K\n\x17previous_season_results\x18\x05 \x01(\x0b\x32*.pogoprotos.data.combat.CombatSeasonResultb\x06proto3'
  ,
  dependencies=[pogoprotos_dot_data_dot_combat_dot_combat__season__result__pb2.DESCRIPTOR,pogoprotos_dot_data_dot_vsseeker_dot_vs__seeker__battle__result__pb2.DESCRIPTOR,])




_COMBATLOG = _descriptor.Descriptor(
  name='CombatLog',
  full_name='pogoprotos.data.combat.CombatLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lifetime_results', full_name='pogoprotos.data.combat.CombatLog.lifetime_results', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_season_results', full_name='pogoprotos.data.combat.CombatLog.current_season_results', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_vs_seeker_set_results', full_name='pogoprotos.data.combat.CombatLog.current_vs_seeker_set_results', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='previous_season_results', full_name='pogoprotos.data.combat.CombatLog.previous_season_results', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=496,
)

_COMBATLOG.fields_by_name['lifetime_results'].message_type = pogoprotos_dot_data_dot_combat_dot_combat__season__result__pb2._COMBATSEASONRESULT
_COMBATLOG.fields_by_name['current_season_results'].message_type = pogoprotos_dot_data_dot_combat_dot_combat__season__result__pb2._COMBATSEASONRESULT
_COMBATLOG.fields_by_name['current_vs_seeker_set_results'].message_type = pogoprotos_dot_data_dot_vsseeker_dot_vs__seeker__battle__result__pb2._VSSEEKERBATTLERESULT
_COMBATLOG.fields_by_name['previous_season_results'].message_type = pogoprotos_dot_data_dot_combat_dot_combat__season__result__pb2._COMBATSEASONRESULT
DESCRIPTOR.message_types_by_name['CombatLog'] = _COMBATLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CombatLog = _reflection.GeneratedProtocolMessageType('CombatLog', (_message.Message,), {
  'DESCRIPTOR' : _COMBATLOG,
  '__module__' : 'pogoprotos.data.combat.combat_log_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.data.combat.CombatLog)
  })
_sym_db.RegisterMessage(CombatLog)


# @@protoc_insertion_point(module_scope)
